### ISSUE TITLE
Correct test errors

### ISSUE THREAD

**Issue by Helmasaur** [Helmasaur/Zodiac-signs#14]
The test file has beenc completed (#9) but `undefined` is returned for values which are linked through a key. It's the case for `element`.

The commented lines are the parts that have to be checked.

**Comment by helmasaur** [comment]
All tests issues but one is linked to the element file. It always returns `undefined` as an element. In a project, it works as expected, but not in tests. I think that the issue comes from the `elements.json` path from the `test/test.js` file.

Refer to #55 for the other issue.

**Comment by helmasaur** [comment]
The test returns:

```
> zodiac-signs@1.5.0 test
> mocha



  zodiac.getSignByDate()
    ✔ should get the zodiac sign's information based on a date
    ✔ should get the zodiac sign's information based on a date (French override)
    ✔ should return the error code -1 when the date is invalid

  zodiac.getSignByName(signName)
    1) should get the zodiac sign's information based on a name
    2) should get the zodiac sign's information based on a date (French override)
    ✔ should return the error code -1 when the name is invalid

  zodiac.getSignBySymbol(signSymbol)
    3) should get the zodiac sign's information based on a symbol
    ✔ should return the error code -1 when the symbol is invalid

  zodiac.getNames()
    ✔ should get the list of zodiac names

  zodiac.getSymbols()
    ✔ should get the list of zodiac symbols

  zodiac.getElements()
    ✔ should get the list of zodiac elements


  8 passing (25ms)
  3 failing

  1) zodiac.getSignByName(signName)
       should get the zodiac sign's information based on a name:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  dateMax: '2000-07-22',
  dateMin: '2000-06-22',
  element: undefined,
  name: 'Cancer',
  stone: 'emerald',
  symbol: '♋'
}

should loosely deep-equal

{
  dateMax: '2000-07-22',
  dateMin: '2000-06-22',
  element: 'water',
  name: 'Cancer',
  stone: 'emerald',
  symbol: '♋'
}
      + expected - actual

       {
         "dateMax": "2000-07-22"
         "dateMin": "2000-06-22"
      -  "element": [undefined]
      +  "element": "water"
         "name": "Cancer"
         "stone": "emerald"
         "symbol": "♋"
       }
      
      at Context.<anonymous> (test/test.js:31:10)
      at process.processImmediate (node:internal/timers:504:21)

  2) zodiac.getSignByName(signName)
       should get the zodiac sign's information based on a date (French override):

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  dateMax: '2000-07-22',
  dateMin: '2000-06-22',
  element: undefined,
  name: 'Cancer',
  stone: 'émeraude',
  symbol: '♋'
}

should loosely deep-equal

{
  dateMax: '2000-07-22',
  dateMin: '2000-06-22',
  element: 'eau',
  name: 'Cancer',
  stone: 'émeraude',
  symbol: '♋'
}
      + expected - actual

       {
         "dateMax": "2000-07-22"
         "dateMin": "2000-06-22"
      -  "element": [undefined]
      +  "element": "eau"
         "name": "Cancer"
         "stone": "émeraude"
         "symbol": "♋"
       }
      
      at Context.<anonymous> (test/test.js:35:10)
      at process.processImmediate (node:internal/timers:504:21)

  3) zodiac.getSignBySymbol(signSymbol)
       should get the zodiac sign's information based on a symbol:

      AssertionError [ERR_ASSERTION]: Expected values to be loosely deep-equal:

{
  dateMax: '2000-07-22',
  dateMin: '2000-06-22',
  element: undefined,
  name: 'Cancer',
  stone: 'emerald',
  symbol: '♋'
}

should loosely deep-equal

{
  dateMax: '2000-07-22',
  dateMin: '2000-06-22',
  element: 'water',
  name: 'Cancer',
  stone: 'emerald',
  symbol: '♋'
}
      + expected - actual

       {
         "dateMax": "2000-07-22"
         "dateMin": "2000-06-22"
      -  "element": [undefined]
      +  "element": "water"
         "name": "Cancer"
         "stone": "emerald"
         "symbol": "♋"
       }
      
      at Context.<anonymous> (test/test.js:52:10)
      at process.processImmediate (node:internal/timers:504:21)
```
